// Generated by scripts/extract-bomb-art.py from installed Isaac ANM2.
export const BOMB_ANIMATION = {
  "fps": 30,
  "cell": 256,
  "columns": 8,
  "rows": 15,
  "anchor": [
    128,
    192
  ],
  "dropFrame": 25,
  "appear": {
    "start": 0,
    "frames": 35
  },
  "pulse": {
    "start": 35,
    "frames": 59
  },
  "explode": {
    "start": 94,
    "frames": 5
  },
  "explosion": {
    "start": 99,
    "frames": 19
  }
} as const
